version: "3"
services:
  jupyter:
    build: docker/jupyter
    image: kaggle/python:latest
    volumes:
      # host側のmount元 path : docker側のmount先path
      - .:/tmp/working
    working_dir: /tmp/working
    ports:
      - 8888:8888
    command: jupyter-lab --ip=0.0.0.0 --allow-root --no-browser --port 8888